### ISSUE TITLE
peer review - natalie huante

### ISSUE THREAD

**Issue by nhuante** [PatrickPolcuch/CPSC354Project#4]
hi all! i really like your project idea of combining coding and music. i think that creating music is a great way for people to learn about programming in a way that is also enjoyable and accessible. in my pull request, i created the outline of a rest block because i noticed that there is currently no way to do so unless you just dont set blocks for a certain beat. this way, the user can explicitly see where they are placing their rests in the measure. i also made sure the measure block accepts rests as well as notes and made sure the note and rest blocks accept each other as valid previous and next connections. my question for you is, how are you going to account for people who are less familiar with some of the input values you are asking for, like time signatures and keys. it would be interesting if you could then convert the blocks into a visual representation of what the song looks like so the user can visually see an end result that is not just blocks.

**Comment by PatrickPolcuch** [comment]
Hello! Thanks for your ideas! I like the idea of rest blocks as a style concept so users can better organize their music. The tricky part about having the rest blocks be more than a visual organizer is that we can currently have more than one note playing at a time. Having the rest block override note blocks might be tricky from a design standpoint. Since we added some more advanced items to the blocks like time signatures and key signatures, we included default values for these items. The user can use the default values, and we hope that the users can gain an understanding of these items by playing with our site. We have been discussing ways in which we can create a visual representation, but we still havent come to a decision.
